#!/bin/bash

if [ $# -ne 2 ];
then
  echo "Incorrect usage!"
  echo $0" <exec> <path>"
  exit 1
fi

HERE=$(dirname $0)
SERVER=$HERE/backend/server
CURL=/usr/bin/curl

killall server

RESPONSE=`$CURL localhost:8083/ping 2>/dev/null`
if [ "$RESPONSE" != "pong" ];
then
  cd $HERE/backend 
  ./server --daemon 
  cd -
  # TODO: Check that server has come up?
fi

URL="localhost:8083/pp/update?exec="$1"&logs="$2
$CURL $URL > /dev/null 2>&1

if [ $? -ne 0 ];
then
  echo "Error sending update message to server!"
  exit 1
fi

exit 0

